// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Cube_2f37b1be90c58714f91aba02c042dfd9Index = 0;
		public const int Cube__char_32_Variant_e8d6920402569dd47b477052885e156bIndex = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Cube_2f37b1be90c58714f91aba02c042dfd9", 0 },

			{ "Cube__char_32_Variant_e8d6920402569dd47b477052885e156b", 1 },

		};
	}
}
