// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_c9d321b103129184eb302bb638fd65ac_112b44b2_d38e_4b8d_83fd_b78c7b041a6f : FloatBinding
	{
		private TreeController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (TreeController)UnityComponent;
		}
		public override string CoherenceComponentName => "Tree_id1_TreeController_6230497222636945137";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.Health);
			set => CastedUnityComponent.Health = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Tree_id1_TreeController_6230497222636945137)coherenceComponent;
			return update.Health;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Tree_id1_TreeController_6230497222636945137)coherenceComponent;
			update.Health = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Tree_id1_TreeController_6230497222636945137();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Tree' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncTree_id1 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncTree_id1>();
			if (coherenceSync.TryGetBindingByGuid("112b44b2-d38e-4b8d-83fd-b78c7b041a6f", "Health", out Binding InternalTree_id1_TreeController_6230497222636945137_Tree_id1_TreeController_6230497222636945137_Health))
			{
				var clone = new Binding_c9d321b103129184eb302bb638fd65ac_112b44b2_d38e_4b8d_83fd_b78c7b041a6f();
				InternalTree_id1_TreeController_6230497222636945137_Tree_id1_TreeController_6230497222636945137_Health.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalTree_id1_TreeController_6230497222636945137_Tree_id1_TreeController_6230497222636945137_Health)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (TreeController).Health");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncTree_id1] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
