// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_id0_PlayerController__char_46_DropPotatoesNet_fd76e0f7_bc0a_40ff_a1ff_6b96f8401cf9 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_id0_PlayerController__char_46_DropPotatoesNet_fd76e0f7_bc0a_40ff_a1ff_6b96f8401cf9;

		public static void Serialize(Player_id0_PlayerController__char_46_DropPotatoesNet_fd76e0f7_bc0a_40ff_a1ff_6b96f8401cf9 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_id0_PlayerController__char_46_DropPotatoesNet_fd76e0f7_bc0a_40ff_a1ff_6b96f8401cf9 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_id0_PlayerController__char_46_DropPotatoesNet_fd76e0f7_bc0a_40ff_a1ff_6b96f8401cf9
			(
			){};
		}
	}
}
