// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct PotatoSpawner_id3_PotatoSpawnerController__char_46_SpawnPotato_f0f695e4_790e_4640_b183_0896fcb6efa4 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPotatoSpawner_id3_PotatoSpawnerController__char_46_SpawnPotato_f0f695e4_790e_4640_b183_0896fcb6efa4;

		public static void Serialize(PotatoSpawner_id3_PotatoSpawnerController__char_46_SpawnPotato_f0f695e4_790e_4640_b183_0896fcb6efa4 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static PotatoSpawner_id3_PotatoSpawnerController__char_46_SpawnPotato_f0f695e4_790e_4640_b183_0896fcb6efa4 Deserialize(IInProtocolBitStream bitStream)
		{

			return new PotatoSpawner_id3_PotatoSpawnerController__char_46_SpawnPotato_f0f695e4_790e_4640_b183_0896fcb6efa4
			(
			){};
		}
	}
}
