// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Tree_id1_TreeController__char_46_RestoreHealthNet_ef71c32f_f905_4f7b_a7cf_278da698afe6 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalTree_id1_TreeController__char_46_RestoreHealthNet_ef71c32f_f905_4f7b_a7cf_278da698afe6;

		public static void Serialize(Tree_id1_TreeController__char_46_RestoreHealthNet_ef71c32f_f905_4f7b_a7cf_278da698afe6 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Tree_id1_TreeController__char_46_RestoreHealthNet_ef71c32f_f905_4f7b_a7cf_278da698afe6 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Tree_id1_TreeController__char_46_RestoreHealthNet_ef71c32f_f905_4f7b_a7cf_278da698afe6
			(
			){};
		}
	}
}
