// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Tree_id1_TreeController__char_46_PanelEndGame_27bde456_5fc5_448a_9a2c_c9fa62de9960 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalTree_id1_TreeController__char_46_PanelEndGame_27bde456_5fc5_448a_9a2c_c9fa62de9960;

		public static void Serialize(Tree_id1_TreeController__char_46_PanelEndGame_27bde456_5fc5_448a_9a2c_c9fa62de9960 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Tree_id1_TreeController__char_46_PanelEndGame_27bde456_5fc5_448a_9a2c_c9fa62de9960 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Tree_id1_TreeController__char_46_PanelEndGame_27bde456_5fc5_448a_9a2c_c9fa62de9960
			(
			){};
		}
	}
}
